name: 'bank_reviews_decisionnal'
version: '1.0'
config-version: 2

profile: 'bank_reviews_decisionnal'

model-paths: ["models"]

models:
  bank_reviews_decisionnal:
    decisionnal:
      +schema: decisionnal
      +materialized: table
